# Generated by Django 5.1.1 on 2025-05-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=30)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('email_cliente', models.EmailField(max_length=255, unique=True)),
                ('direccion_cliente', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
