# Generated by Django 5.1.1 on 2025-05-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido_proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('empresa_proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('email_empresa', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido_cliente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
