# Generated by Django 5.1.1 on 2025-05-12 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_empleado_metodos_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='email_empresa',
            new_name='email_empresa_proveedor',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido_cliente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion_cliente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_cliente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email_empleado',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='apellido_proveedor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='empresa_proveedor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_proveedor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_proveedor',
            field=models.CharField(max_length=50),
        ),
        migrations.RenameModel(
            old_name='Metodos_pago',
            new_name='MetodoPago',
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('cantidad_producto_pedido', models.IntegerField()),
                ('cliente_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('empleado_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleado')),
                ('nombre_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('tipo_metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.metodopago')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('pedido_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
            ],
        ),
    ]
