# Generated by Django 5.1.1 on 2025-05-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_email_empresa_proveedor_email_empresa_proveedor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad_producto',
            new_name='cantidad_producto_stock',
        ),
    ]
